# Generated by Django 4.2.20 on 2025-03-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="cover_image",
            field=models.ImageField(default="blog_default.jpg", upload_to=""),
        ),
    ]
